export type CustomerStatus = "aktiv" | "wartung-faellig" | "saison-pause" | "neu" | "vip";
export type CustomerType = "privat" | "gewerbe" | "oeffentlich";
export type Service =
  | "rasenpflege"
  | "heckenschnitt"
  | "baumpflege"
  | "bewaesserung"
  | "pflanzplanung"
  | "winterdienst"
  | "teichbau"
  | "natursteinarbeiten";
export type GardenType =
  | "ziergarten"
  | "nutzgarten"
  | "dachgarten"
  | "park"
  | "firmengelaende"
  | "gastgarten";

export type Customer = {
  id: string;
  name: string;
  type: CustomerType;
  address: {
    street: string;
    city: string;
    postalCode: string;
    district: string;
  };
  coordinates: [number, number];
  status: CustomerStatus;
  services: Service[];
  gardenType: GardenType;
  gardenSizeM2: number;
  customerSince: string;
  lastVisit: string;
  nextAppointment?: string;
  yearlyRevenueEur: number;
  notes: string;
  photoUrl: string;
  hasSplatDemo?: boolean;
  splatEmbedUrl?: string;
};

const SPLAT_EMBED_URL = "https://lumalabs.ai/embed/ca9ea966-ca24-4ec1-ab0f-af2f97f5dfa3";

export const customers: Customer[] = [
  {
    id: "c-001",
    name: "Villa Hofer",
    type: "privat",
    address: {
      street: "Pöstlingbergstraße 12",
      city: "Linz",
      postalCode: "4040",
      district: "Pöstlingberg",
    },
    coordinates: [14.2515, 48.3175],
    status: "vip",
    services: ["rasenpflege", "heckenschnitt", "baumpflege", "pflanzplanung", "natursteinarbeiten"],
    gardenType: "ziergarten",
    gardenSizeM2: 1850,
    customerSince: "2018-04-12",
    lastVisit: "2026-04-28",
    nextAppointment: "2026-05-21",
    yearlyRevenueEur: 18_400,
    notes:
      "Premium-Ziergarten mit historischen Sandsteinmauern, japanischem Ahorn und mediterraner Bepflanzung. Familie wünscht sich für 2026 eine Erweiterung des Wassergartens. Hauptansprechpartnerin: Frau Dr. Hofer.",
    photoUrl: "/photos/c-001.svg",
    hasSplatDemo: true,
    splatEmbedUrl: SPLAT_EMBED_URL,
  },
  {
    id: "c-002",
    name: "Familie Gruber",
    type: "privat",
    address: {
      street: "Bachlbergweg 28",
      city: "Linz",
      postalCode: "4040",
      district: "Pöstlingberg",
    },
    coordinates: [14.2495, 48.3198],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "winterdienst"],
    gardenType: "ziergarten",
    gardenSizeM2: 720,
    customerSince: "2021-06-03",
    lastVisit: "2026-04-15",
    nextAppointment: "2026-05-15",
    yearlyRevenueEur: 4_200,
    notes: "Familienhaus mit Aussicht. Großer Rasen, schattige Bereiche unter Buchen.",
    photoUrl: "/photos/c-002.svg",
  },
  {
    id: "c-003",
    name: "Familie Mayrhofer",
    type: "privat",
    address: {
      street: "Reuchlinstraße 14",
      city: "Linz",
      postalCode: "4040",
      district: "Urfahr",
    },
    coordinates: [14.2867, 48.3142],
    status: "aktiv",
    services: ["rasenpflege", "pflanzplanung"],
    gardenType: "nutzgarten",
    gardenSizeM2: 380,
    customerSince: "2022-09-18",
    lastVisit: "2026-04-22",
    nextAppointment: "2026-05-19",
    yearlyRevenueEur: 2_800,
    notes: "Permakultur-Garten mit Hochbeeten und Obstspalieren. Sehr selbstbestimmte Planung.",
    photoUrl: "/photos/c-003.svg",
  },
  {
    id: "c-004",
    name: "Familie Steininger",
    type: "privat",
    address: {
      street: "Ferihumerstraße 41",
      city: "Linz",
      postalCode: "4040",
      district: "Urfahr",
    },
    coordinates: [14.2823, 48.3158],
    status: "wartung-faellig",
    services: ["baumpflege", "heckenschnitt"],
    gardenType: "ziergarten",
    gardenSizeM2: 560,
    customerSince: "2019-03-21",
    lastVisit: "2025-11-08",
    nextAppointment: "2026-05-16",
    yearlyRevenueEur: 3_100,
    notes: "Letzter Heckenschnitt im November. Robinie hat Sturmschaden, Baumpflege dringend.",
    photoUrl: "/photos/c-004.svg",
  },
  {
    id: "c-005",
    name: "Familie Brandstätter",
    type: "privat",
    address: {
      street: "Lunaplatz 8",
      city: "Linz",
      postalCode: "4030",
      district: "Solar City",
    },
    coordinates: [14.3782, 48.2335],
    status: "saison-pause",
    services: ["rasenpflege", "bewaesserung"],
    gardenType: "dachgarten",
    gardenSizeM2: 95,
    customerSince: "2023-05-11",
    lastVisit: "2025-10-04",
    yearlyRevenueEur: 1_650,
    notes:
      "Dachgarten auf Solar-City-Reihenhaus. Tropfbewässerung im Winter pausiert. Wiederaufnahme im Mai.",
    photoUrl: "/photos/c-005.svg",
  },
  {
    id: "c-006",
    name: "Familie Kaltenböck",
    type: "privat",
    address: {
      street: "Sonnenparkstraße 22",
      city: "Linz",
      postalCode: "4030",
      district: "Solar City",
    },
    coordinates: [14.3795, 48.2348],
    status: "aktiv",
    services: ["rasenpflege", "bewaesserung", "pflanzplanung"],
    gardenType: "ziergarten",
    gardenSizeM2: 410,
    customerSince: "2020-08-30",
    lastVisit: "2026-04-19",
    nextAppointment: "2026-05-17",
    yearlyRevenueEur: 3_400,
    notes: "Architektenhaus. Klare Linien, ein Olivenbaum im Zentrum.",
    photoUrl: "/photos/c-006.svg",
  },
  {
    id: "c-007",
    name: "Familie Pöschl",
    type: "privat",
    address: {
      street: "Wiener Straße 156",
      city: "Linz",
      postalCode: "4030",
      district: "Ebelsberg",
    },
    coordinates: [14.3578, 48.2445],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "teichbau"],
    gardenType: "ziergarten",
    gardenSizeM2: 890,
    customerSince: "2017-05-04",
    lastVisit: "2026-04-25",
    nextAppointment: "2026-05-23",
    yearlyRevenueEur: 5_900,
    notes: "Großer Teich mit Koi-Karpfen. UV-Klärung Wartung jährlich. Familie sehr designaffin.",
    photoUrl: "/photos/c-007.svg",
  },
  {
    id: "c-008",
    name: "Familie Aigner",
    type: "privat",
    address: {
      street: "Keferfeldstraße 76",
      city: "Linz",
      postalCode: "4020",
      district: "Keferfeld",
    },
    coordinates: [14.2727, 48.2748],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt"],
    gardenType: "ziergarten",
    gardenSizeM2: 320,
    customerSince: "2022-04-14",
    lastVisit: "2026-04-18",
    nextAppointment: "2026-05-15",
    yearlyRevenueEur: 2_100,
    notes: "Reihenhausgarten mit Kletterrosen.",
    photoUrl: "/photos/c-008.svg",
  },
  {
    id: "c-009",
    name: "Familie Lehner",
    type: "privat",
    address: {
      street: "Welser Straße 89",
      city: "Leonding",
      postalCode: "4060",
      district: "Leonding",
    },
    coordinates: [14.2515, 48.2792],
    status: "aktiv",
    services: ["rasenpflege", "winterdienst"],
    gardenType: "ziergarten",
    gardenSizeM2: 480,
    customerSince: "2020-11-15",
    lastVisit: "2026-04-21",
    nextAppointment: "2026-05-19",
    yearlyRevenueEur: 2_700,
    notes: "Großer Magnolienbaum als Hingucker, Familie mit drei Kindern.",
    photoUrl: "/photos/c-009.svg",
  },
  {
    id: "c-010",
    name: "Familie Stadler",
    type: "privat",
    address: {
      street: "Hauptstraße 45",
      city: "Leonding",
      postalCode: "4060",
      district: "Leonding",
    },
    coordinates: [14.2531, 48.2818],
    status: "neu",
    services: ["pflanzplanung", "natursteinarbeiten"],
    gardenType: "ziergarten",
    gardenSizeM2: 640,
    customerSince: "2026-03-09",
    lastVisit: "2026-04-30",
    nextAppointment: "2026-05-22",
    yearlyRevenueEur: 9_200,
    notes:
      "Neukunde: kompletter Gartenneubau geplant. Erstgespräch im März, erste Pflanzphase ab Mai. Sehr ambitioniertes Projekt.",
    photoUrl: "/photos/c-010.svg",
  },
  {
    id: "c-011",
    name: "Familie Höller",
    type: "privat",
    address: {
      street: "Traunerstraße 22",
      city: "Traun",
      postalCode: "4050",
      district: "Traun",
    },
    coordinates: [14.2342, 48.2245],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "winterdienst"],
    gardenType: "nutzgarten",
    gardenSizeM2: 540,
    customerSince: "2019-09-12",
    lastVisit: "2026-04-17",
    nextAppointment: "2026-05-14",
    yearlyRevenueEur: 3_200,
    notes: "Naturnaher Garten, Insektenhotels selbst gebaut.",
    photoUrl: "/photos/c-011.svg",
  },
  {
    id: "c-012",
    name: "Anwesen Wimmer",
    type: "privat",
    address: {
      street: "Wilheringer Straße 18",
      city: "Wilhering",
      postalCode: "4073",
      district: "Wilhering",
    },
    coordinates: [14.2014, 48.3053],
    status: "vip",
    services: [
      "rasenpflege",
      "heckenschnitt",
      "baumpflege",
      "bewaesserung",
      "pflanzplanung",
      "winterdienst",
    ],
    gardenType: "park",
    gardenSizeM2: 4_200,
    customerSince: "2015-02-25",
    lastVisit: "2026-04-26",
    nextAppointment: "2026-05-20",
    yearlyRevenueEur: 26_800,
    notes:
      "Historisches Anwesen an der Donau. Allee mit Linden, Rosengarten, Obstwiese. Wöchentliche Betreuung in der Saison.",
    photoUrl: "/photos/c-012.svg",
  },
  {
    id: "c-013",
    name: "Familie Plöchl",
    type: "privat",
    address: {
      street: "Hauptstraße 67",
      city: "Gallneukirchen",
      postalCode: "4203",
      district: "Gallneukirchen",
    },
    coordinates: [14.4172, 48.3548],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt"],
    gardenType: "nutzgarten",
    gardenSizeM2: 430,
    customerSince: "2021-08-04",
    lastVisit: "2026-04-20",
    nextAppointment: "2026-05-18",
    yearlyRevenueEur: 2_500,
    notes: "Selbstversorger-Garten, Familie tauscht Saatgut.",
    photoUrl: "/photos/c-013.svg",
  },
  {
    id: "c-014",
    name: "Familie Eder",
    type: "privat",
    address: {
      street: "Schlossgasse 4",
      city: "Steyregg",
      postalCode: "4221",
      district: "Steyregg",
    },
    coordinates: [14.3596, 48.3032],
    status: "aktiv",
    services: ["rasenpflege", "natursteinarbeiten"],
    gardenType: "ziergarten",
    gardenSizeM2: 680,
    customerSince: "2018-10-19",
    lastVisit: "2026-04-23",
    nextAppointment: "2026-05-16",
    yearlyRevenueEur: 4_300,
    notes: "Garten am Schlossberg, Trockenmauern aus Granit.",
    photoUrl: "/photos/c-014.svg",
  },
  {
    id: "c-015",
    name: "Familie Reiter",
    type: "privat",
    address: {
      street: "Linzer Straße 31",
      city: "Engerwitzdorf",
      postalCode: "4209",
      district: "Engerwitzdorf",
    },
    coordinates: [14.3958, 48.3475],
    status: "aktiv",
    services: ["rasenpflege", "winterdienst"],
    gardenType: "ziergarten",
    gardenSizeM2: 510,
    customerSince: "2023-04-07",
    lastVisit: "2026-04-29",
    nextAppointment: "2026-05-24",
    yearlyRevenueEur: 2_400,
    notes: "Neubau mit Beerenobst-Schwerpunkt.",
    photoUrl: "/photos/c-015.svg",
  },
  {
    id: "c-016",
    name: "Hotel Wolfinger",
    type: "gewerbe",
    address: {
      street: "Hauptplatz 19",
      city: "Linz",
      postalCode: "4020",
      district: "Innenstadt",
    },
    coordinates: [14.2858, 48.3061],
    status: "vip",
    services: ["heckenschnitt", "pflanzplanung", "bewaesserung", "natursteinarbeiten"],
    gardenType: "gastgarten",
    gardenSizeM2: 280,
    customerSince: "2016-05-30",
    lastVisit: "2026-04-27",
    nextAppointment: "2026-05-13",
    yearlyRevenueEur: 14_200,
    notes:
      "Innenhof-Gastgarten mit Buchsbaum-Skulpturen und historischen Steintrögen. Aufwertung 2025 mit Lichtkonzept.",
    photoUrl: "/photos/c-016.svg",
    hasSplatDemo: true,
    splatEmbedUrl: SPLAT_EMBED_URL,
  },
  {
    id: "c-017",
    name: "Restaurant Stadtkrämerei",
    type: "gewerbe",
    address: {
      street: "Landstraße 26",
      city: "Linz",
      postalCode: "4020",
      district: "Innenstadt",
    },
    coordinates: [14.2865, 48.3018],
    status: "vip",
    services: ["bewaesserung", "pflanzplanung", "heckenschnitt"],
    gardenType: "gastgarten",
    gardenSizeM2: 140,
    customerSince: "2019-04-22",
    lastVisit: "2026-04-24",
    nextAppointment: "2026-05-15",
    yearlyRevenueEur: 7_800,
    notes: "Innenhof mit Hochbeeten für Küchenkräuter — Köchin lebt für saisonale Eigenproduktion.",
    photoUrl: "/photos/c-017.svg",
  },
  {
    id: "c-018",
    name: "Klosterhof Linz",
    type: "gewerbe",
    address: {
      street: "Landstraße 30",
      city: "Linz",
      postalCode: "4020",
      district: "Innenstadt",
    },
    coordinates: [14.2867, 48.3015],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "natursteinarbeiten"],
    gardenType: "gastgarten",
    gardenSizeM2: 360,
    customerSince: "2017-07-11",
    lastVisit: "2026-04-25",
    nextAppointment: "2026-05-17",
    yearlyRevenueEur: 6_600,
    notes: "Historischer Klosterhof. Strenge Auflagen Denkmalschutz bei jeder Maßnahme.",
    photoUrl: "/photos/c-018.svg",
  },
  {
    id: "c-019",
    name: "Tabakfabrik Linz",
    type: "gewerbe",
    address: {
      street: "Peter-Behrens-Platz 10",
      city: "Linz",
      postalCode: "4020",
      district: "Tabakfabrik",
    },
    coordinates: [14.2945, 48.2942],
    status: "aktiv",
    services: ["rasenpflege", "pflanzplanung", "winterdienst"],
    gardenType: "firmengelaende",
    gardenSizeM2: 2_100,
    customerSince: "2020-01-15",
    lastVisit: "2026-04-22",
    nextAppointment: "2026-05-20",
    yearlyRevenueEur: 12_400,
    notes: "Industriedenkmal-Campus, urban gardening Initiative der Mieter unterstützen.",
    photoUrl: "/photos/c-019.svg",
  },
  {
    id: "c-020",
    name: "Donauschiff Restaurant",
    type: "gewerbe",
    address: {
      street: "Donaulände 5",
      city: "Linz",
      postalCode: "4020",
      district: "Donaulände",
    },
    coordinates: [14.2895, 48.3092],
    status: "aktiv",
    services: ["pflanzplanung", "bewaesserung"],
    gardenType: "gastgarten",
    gardenSizeM2: 90,
    customerSince: "2022-05-09",
    lastVisit: "2026-04-19",
    nextAppointment: "2026-05-14",
    yearlyRevenueEur: 3_600,
    notes: "Kübelbepflanzung auf Schiffsdeck, salzwasserresistent.",
    photoUrl: "/photos/c-020.svg",
  },
  {
    id: "c-021",
    name: "Plus City Pasching",
    type: "gewerbe",
    address: {
      street: "Pluskaufstraße 7",
      city: "Pasching",
      postalCode: "4061",
      district: "Pasching",
    },
    coordinates: [14.201, 48.2697],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "winterdienst"],
    gardenType: "firmengelaende",
    gardenSizeM2: 5_400,
    customerSince: "2014-10-01",
    lastVisit: "2026-04-30",
    nextAppointment: "2026-05-13",
    yearlyRevenueEur: 31_500,
    notes: "Großauftrag: Außenflächen Shopping Center, inkl. Winterdienst Parkplätze.",
    photoUrl: "/photos/c-021.svg",
  },
  {
    id: "c-022",
    name: "Lentos Café",
    type: "gewerbe",
    address: {
      street: "Ernst-Koref-Promenade 1",
      city: "Linz",
      postalCode: "4020",
      district: "Donaulände",
    },
    coordinates: [14.2902, 48.3072],
    status: "aktiv",
    services: ["pflanzplanung", "bewaesserung"],
    gardenType: "gastgarten",
    gardenSizeM2: 110,
    customerSince: "2023-04-04",
    lastVisit: "2026-04-26",
    nextAppointment: "2026-05-15",
    yearlyRevenueEur: 4_100,
    notes: "Museums-Café mit Donaublick. Minimalistische Bepflanzung im Architekturkonzept.",
    photoUrl: "/photos/c-022.svg",
  },
  {
    id: "c-023",
    name: "Volksgarten Linz",
    type: "oeffentlich",
    address: {
      street: "Volksgartenstraße",
      city: "Linz",
      postalCode: "4020",
      district: "Innenstadt",
    },
    coordinates: [14.2925, 48.2998],
    status: "wartung-faellig",
    services: ["baumpflege", "rasenpflege", "natursteinarbeiten"],
    gardenType: "park",
    gardenSizeM2: 38_000,
    customerSince: "2013-03-15",
    lastVisit: "2025-11-12",
    nextAppointment: "2026-05-22",
    yearlyRevenueEur: 42_000,
    notes:
      "Stadtpark. Pflanzpläne 2026 vom Magistrat unterschrieben, Baumstatik nach Sturm Anfang April neu zu bewerten.",
    photoUrl: "/photos/c-023.svg",
  },
  {
    id: "c-024",
    name: "BG/BRG Khevenhüller",
    type: "oeffentlich",
    address: {
      street: "Khevenhüllerstraße 1",
      city: "Linz",
      postalCode: "4020",
      district: "Bulgariplatz",
    },
    coordinates: [14.2918, 48.2972],
    status: "aktiv",
    services: ["rasenpflege", "baumpflege"],
    gardenType: "firmengelaende",
    gardenSizeM2: 4_800,
    customerSince: "2019-09-02",
    lastVisit: "2026-04-22",
    nextAppointment: "2026-05-20",
    yearlyRevenueEur: 9_400,
    notes: "Schulhof. Schüler-Beteiligungsprojekte bei Pflanzaktionen.",
    photoUrl: "/photos/c-024.svg",
  },
  {
    id: "c-025",
    name: "St.-Barbara-Friedhof",
    type: "oeffentlich",
    address: {
      street: "Barbarafriedhofstraße 5",
      city: "Linz",
      postalCode: "4020",
      district: "Bulgariplatz",
    },
    coordinates: [14.2848, 48.2925],
    status: "aktiv",
    services: ["rasenpflege", "heckenschnitt", "baumpflege", "natursteinarbeiten"],
    gardenType: "park",
    gardenSizeM2: 22_000,
    customerSince: "2011-04-18",
    lastVisit: "2026-04-28",
    nextAppointment: "2026-05-21",
    yearlyRevenueEur: 18_900,
    notes: "Friedhof in zentraler Lage. Pietätsthema, daher früher Beginn und leise Arbeitsweise.",
    photoUrl: "/photos/c-025.svg",
  },
];

export const customersById: Record<string, Customer> = Object.fromEntries(
  customers.map((c) => [c.id, c]),
);

export type CustomersIndex = typeof customersById;
